# Generated by Django 3.2 on 2022-11-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('object_id', models.IntegerField(primary_key=True, serialize=False)),
                ('asset_id', models.CharField(max_length=50)),
                ('asset_name', models.CharField(max_length=50)),
                ('asset_stat', models.CharField(max_length=50)),
                ('segment_id', models.CharField(max_length=50)),
                ('route_id', models.CharField(max_length=50)),
                ('route_name', models.CharField(default='4', max_length=50)),
                ('route_class', models.CharField(default='1', max_length=50)),
                ('county_id', models.CharField(default='secondary', max_length=50)),
                ('division_id', models.CharField(default='4444444', max_length=50)),
            ],
        ),
    ]
